/*

 ALLEYWAY.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\ahris\Dropbox\LinuxDocuments\AdultWork\CTF2017\squareCTF2017\assets\alleyway.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 48
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define alleywayWidth 20
#define alleywayHeight 18
#define alleywayBank 0

extern unsigned char alleyway[];

/* End of ALLEYWAY.H */
