/*

 ALLEYWAY.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 21 x 19
   Tile set      : Z:\home\ahris\Dropbox\LinuxDocuments\AdultWork\CTF2017\squareCTF2017\assets\alleyway.gbr
   Plane count   : 0.5 plane (4 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define alleywayWidth 21
#define alleywayHeight 19
#define alleywayBank 0

extern unsigned char alleyway[];

/* End of ALLEYWAY.H */
