/*

 GRASS_FIELD.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : Z:\Development\CTF2017\assets\grass.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define grass_fieldWidth 32
#define grass_fieldHeight 32
#define grass_fieldBank 0

extern unsigned char grass_field[];

/* End of GRASS_FIELD.H */
