/*

 TEXT_BOX.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 6
   Tile set      : text_box_border_2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 128
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define text_boxWidth 20
#define text_boxHeight 6
#define text_boxBank 0

extern unsigned char text_box[];

/* End of TEXT_BOX.H */
