/*

 TV_NOISE_1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 12
   Tile set      : Z:\home\ahris\Dropbox\LinuxDocuments\AdultWork\CTF2017\squareCTF2017\assets\black_and_white.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define tv_static_1Width 20
#define tv_static_1Height 12
#define tv_static_1Bank 0

#define tv_static_1 tv_static_1PLN0
extern unsigned char tv_static_1PLN0[];

/* End of TV_NOISE_1.H */
